/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.miltenplescott.tictactoe;

import com.github.miltenplescott.tictactoe.view.Frame;

public class Main {

	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		System.out.println(new Main().getGreeting());

		Frame.getInstance();

	}
}
